### ISSUE TITLE
Remove redundant recipient bars when narrowed in PM / Streams.

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#7]
Currently ZT only clubs those messages it can see, or removes recipient bars for the current message based on the past message. This should be implemented as in Web app.
- [ ] Remove redundant recipient bars as in Web app.
- [x] Add a current message stream and topic ( or name of user )  info at the top of ZT.

**Comment by neiljp** [comment]
Is this fixed now?

**Comment by amanagr** [comment]
The recipient bar behaviour is still not consistent and needs improvement in the displaying new messages end.

**Comment by neiljp** [comment]
I think this is close now (after #167), but just needs the rendering of messages composed/replied by the user within ZT?

**Comment by neiljp** [comment]
@amanagr Could you clarify your position on this, particularly if #179 looks good?

**Comment by amanagr** [comment]
Yup! I think we can close this now. Thanks @neiljp
